#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8
import pgdb
conn = pgdb.connect('localhost:testdb:postgres')

def vivod_all():
    cur = conn.cursor()
    cur.execute("select * from phbook")
    rows = cur.fetchall()
    for row in rows:
        print row[0], row[1], row[2]
    cur.close()

def insert_phbook(in_person, in_post, in_tel):
    cur = conn.cursor()
    cur.execute("insert into phbook (person, post, phone) values (?,?,? )", (in_person, in_post, in_tel))
    conn.commit()
    print "Запись сделанна"
    conn.close()
    #print in_person

print '1) Вывести все записи'
print '2) Добавить запись'
print '3) Удалить все записи'
str = input("Выберите значение: ");
#print "Received input is : ",str
if str == 1:
    vivod_all()
else:
    if str == 2:
        in_person = raw_input("Введите ФИО: ");
        in_post = raw_input("Введите должность: ");
        in_phone = raw_input("Введите телефон: ");
        insert_phbook(in_person, in_post, in_phone)
    else:
        if str == 3:
            print 'Нажад 3'

