#! /usr/bin/env python
import pgdb
conn = pgdb.connect('localhost:testdb:postgres')

def vivod_all():
    cur = conn.cursor()
    cur.execute("select * from phbook")
    rows = cur.fetchall()
    for row in rows:
        print row[0], row[1], row[2]
    cur.close()

def insert_phbook():
    cur = conn.cursor()
    cur.execute('insert ')
