#! /usr/bin/env python
import pgdb
conn = pgdb.connect('localhost:testdb:postgres')

def vivod_all():
    cur = conn.cursor()
    cur.execute("select * from phbook")
    rows = cur.fetchall()
    for row in rows:
        print row[0], row[1], row[2]
    cur.close()

def insert_phbook():
    cur = conn.cursor()
    cur.execute("insert into phbook (person, post, phone) values ('Алекс Иванов', 'специалсит', '345-90-48' )")
    conn.commit()
    print "Запись сделанна"
    conn.close()

#insert_phbook()
print "+++++++++++++++++++++++++++++"
vivod_all()

